const parkingData = [
  { permit:"A1 - Alcala W. Proximity", assigned:"A1 24/7, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"CSDP - Camino SD Proximity", assigned:"CSD PX, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"E2 - SAPS Proximity", assigned:"E2, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"E9 - Vistas E. Proximity", assigned:"E9 24/7, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"E12 - Vistas W. Proximity", assigned:"E12 24/7, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"G1 - IPJ Garage Proximity Annual", assigned:"G1, G2, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"G1 - IPJ Garage Proximity Semester", assigned:"G1, G2, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"G2 - MRHH Garage Proximity Annual", assigned:"G2, G1, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"G2 - MRHH Garage Proximity Semester", assigned:"G2, G1, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"G3 - Manchester N. Proximity", assigned:"G3 24/7, WPS, W1, W2, MPS, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"N1 - UC N. Proximity", assigned:"N1, N2, IE, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"N2 - UC W. Proximity", assigned:"N2, N1, IE, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"IE - Immaculata E. Proximity", assigned:"IE, N2, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"P1 - PTA Proximity", assigned:"P1 24/7, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"S8 - Hughes W. Lot Proximity", assigned:"S8, S9, CSD, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"S9 - Hughes E./Saints W. Lot Proximity", assigned:"S9, S8, CSD, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"S11 - Law Lot Proximity", assigned:"S11 PX, S12, S13, S14, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"S13 - DAC Lot Proximity", assigned:"S13, S11, S12, S14, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"S14 - LRC E. Lot Proximity", assigned:"S14, S11, S12, S13, WPS, W1, W2, MPS, G3, G4, E6, E11", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"Faculty/Staff Annual", assigned:"MPS, E3, E5, E8, E11, W3, W4, WPS, W1, W2, G3, G4, E6", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"Emeritus/Retired", assigned:"MPS, E3, E5, E8, E11, W3, W4, WPS, W1, W2, G3, G4, E6", offpeak:"All PX Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"West Parking Annual/Semester", assigned:"WPS, W1, W2, G3, G4, E6", offpeak:"FS and C Lots", overflow:"N/A" },
  { permit:"West Parking ROTC", assigned:"WPS, W1, W2, G3, G4, E6", offpeak:"FS and C Lots", overflow:"N/A" },
  { permit:"PR - Perimeter", assigned:"WPS Basement L1-L3, W2, G3, G4, E6", offpeak:"WPS, W1", overflow:"N/A" },
  { permit:"Motorcycle Scooter Annual", assigned:"Designated Motorcycle Spaces Only", offpeak:"Designated Motorcycle Spaces Only", overflow:"N/A" },
  { permit:"Student Commuter Annual/Semester", assigned:"WPS, W1, W2, Manion Way, Marian Way, N5, N3, MPS, E3, E10AVC, MPS, S12, S11, S10, CSDC, G3, G4, E6", offpeak:"All PX and FS Lots", overflow:"MPS, WPS, W1, W2, G3, G4, E6" },
  { permit:"First Year Resident Annual/Semester", assigned:"W2, G3, G4, E6", offpeak:"All C, FS, and PX Lots", overflow:"N/A" },
  { permit:"Resident Camino Founders Annual/Semester", assigned:"WPS, W1, W2, G3, G4, E6", offpeak:"All C, FS, and PX Lots", overflow:"N/A" },
  { permit:"Resident Manchester Annual/Semester", assigned:"G3, G4, WPS, W1, W2, E6; All C, FS, and PX lots after 4pm Monday-Friday", offpeak:"All C, FS, and PX Lots", overflow:"N/A" },
  { permit:"Resident PRidge (Manchester) Annual/Semester", assigned:"G3, G4, WPS, W1, W2, E6", offpeak:"All C, FS, and PX Lots", overflow:"N/A" },
  { permit:"Resident PTA Semester", assigned:"PTA, WPS, W1, W2, G3, G4, E6", offpeak:"All C, FS, and PX Lots", overflow:"N/A" },
  { permit:"Resident Valley Annual", assigned:"MPS, E1, E2, SA, SB, SD, SP, WPS, W1, W2, G3, G4, E6", offpeak:"All C, FS, and PX Lots", overflow:"N/A" },
  { permit:"Resident Vista Annual", assigned:"E9, E10, E12, E10AVC, WPS, W1, W2, G3, G4, E6", offpeak:"All C, FS, and PX Lots", overflow:"N/A" },
];